services:
    Okwind\TempoTelemetryBundle\Telemetry\Tempo:
        public: true
        class: "Okwind\\TempoTelemetryBundle\\Telemetry\\Tempo"
        arguments:
            - '@logger'
            - '%Okwind.tempo_telemetry.service_name%'
            - '%Okwind.tempo_telemetry.tempo_url%'
            - '%Okwind.tempo_telemetry.timeout%'
    Okwind\TempoTelemetryBundle\Telemetry\DebugStack:
        public: true
        class: "Okwind\\TempoTelemetryBundle\\Telemetry\\DebugStack"
        arguments:
            - '@Okwind\TempoTelemetryBundle\Telemetry\Tempo'
